sudo: required
language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.1
    - android-26
    - extra-android-m2repository
deploy:
  provider: script
  script: ./gradlew publishApkRelease
  on:
    tags: true
